service: mark-hub
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: build/hub.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin